services:
  app:
    build: .
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "${APP_PORT:-3200}:8000"
    environment:
      ENV: development
      DATABASE_URL: ${DATABASE_URL:-postgresql://app:${POSTGRES_PASSWORD:-password}@database:5432/${POSTGRES_DB:-data}}
    restart: unless-stopped

  database:
    restart: unless-stopped
    image: postgres:${POSTGRES_VERSION:-17}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-data}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - 5432
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB:-data}",
          "-U",
          "${POSTGRES_USER:-app}",
        ]
      timeout: 5s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data: {}
