"""Create MaltProfile table

Revision ID: e07842353b59
Revises: 
Create Date: 2025-02-23 15:45:28.935051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07842353b59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('malt_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('daily_rate', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('missions_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('experience', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_malt_profiles_fullname'), 'malt_profiles', ['fullname'], unique=False)
    op.create_index(op.f('ix_malt_profiles_id'), 'malt_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_malt_profiles_profile_id'), 'malt_profiles', ['profile_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_malt_profiles_profile_id'), table_name='malt_profiles')
    op.drop_index(op.f('ix_malt_profiles_id'), table_name='malt_profiles')
    op.drop_index(op.f('ix_malt_profiles_fullname'), table_name='malt_profiles')
    op.drop_table('malt_profiles')
    # ### end Alembic commands ###
