name: Trigger Webhook

on:
  workflow_run:
    workflows: [build-and-push-docker-image]
    types:
      - completed
    branches:
      - main
      - preprod

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Debug Information
        run: |
          echo "Workflow event: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"

      - name: deploy scrapper production
        run: |
          curl -X GET "${{ secrets.WEBHOOK_SCRAPPER_PRODUCTION }}" \
            -H "Authorization: Bearer ${{ secrets.WEBHOOK_TOKEN }}"
